### ISSUE TITLE
How to use? display "/sdcard/sh.png: 1 file pulled. 36.1 MB/s (2302937 bytes in 0.061s)" 

### ISSUE THREAD

**Issue by Kennnnnnji** [Meowcolm024/FGO-Automata#1]
after running `python main.py`
![QQ截图20191102123418](https://user-images.githubusercontent.com/34367558/68066060-25443380-fd6d-11e9-9282-dde95e7fe7d8.png)
platform: Windows 10, Python 3.7.2, Mi Mix2S, Android 9

**Comment by Kennnnnnji** [comment]
and sh.png is like this:
![sh](https://user-images.githubusercontent.com/34367558/68066101-94ba2300-fd6d-11e9-924e-a9de74a947c1.png)
Seems image is not correct...

**Comment by Meowcolm024** [comment]
Obliviously you haven't understood how this thing works.
The `main.py` and `main2.py` included in the repo is designed specifically for my situation, you may need to write yourself your own script.
Here are steps you may need to follow:
1. take a screenshot of the checkpoint and support page and try to make the template image of the desired checkpoint and support(see: [Making Templates](https://github.com/Meowcolm024/FGO-Automata#making-templates))
2. then you can either put the two images in the `root` directory or in the `assets` folder.
3. follow the [Reference](https://github.com/Meowcolm024/FGO-Automata#references) to write your own configuration of the battle
But notice that there is still some issues with the selecting support function as it could only select the first 3 and make sure your party could pass the battle exactly following your code.
