### ISSUE TITLE
A bug in Scripter.py

### ISSUE THREAD

**Issue by Tsuasahi** [Meowcolm024/FGO-Automata#21]
When I select Servant skill with a target  by REPL, the REPL will select a target and return

> Traceback (most recent call last):
>   File "REPL.py", line 7, in <module>
>     repl.main_loop()
>   File "C:\fakepath\FGO-Automata\core\Scripter.py", line 141, in main_loop
>     print(self.itp.evaluate(cmd.replace(' ', '')))
>   File "C:\fakepath\FGO-Automata\core\Scripter.py", line 62, in evaluate
>     return self._eval(cmd)
>   File "C:\fakepath\FGO-Automata\core\Scripter.py", line 103, in _eval
>     return ('Servant skill: ' + out)
> TypeError: can only concatenate str (not "list") to str

I try changing **line 103** in Scripter.py
from   `return ('Servant skill: ' + out)`   to   `return ('Servant skill: ' + str(out))`  ,
then it seem to run well.

**Comment by Meowcolm024** [comment]
Oops!
要不你直接改吧：）

**Comment by Tsuasahi** [comment]
okk :D
