### ISSUE TITLE
適配非國服FGO問題

### ISSUE THREAD

**Issue by Zhen-Bo** [Meowcolm024/FGO-Automata#23]
Language: 
  - 中文

如果我把assets資料夾內的圖片改成日/美/台服的對應圖片的話,這樣是不是就能無痛適配非國服的FGO了Orz

**Comment by Meowcolm024** [comment]
雖然理論上是這樣，但Fate/GO日服和美服是aniplex運營的，遊戲是無法在開啟**USB偵錯**的情況下啟動的。這樣看來估計只有**繁體中文**服可以用。（但我自己沒測試過，所以不能確定orz

**Comment by Zhen-Bo** [comment]
新版的日服FGO已經可以在ROOT+USB偵錯機上啟動了
我之後再去試試,感謝Orz
