### ISSUE TITLE
A little tiny question: The program keeps capturing the screen but couldn't reach next motion.

### ISSUE THREAD

**Issue by LorCamlot** [Meowcolm024/FGO-Automata#24]
Language: 
  - 中文
### 运行代码（自创py文件：chentu.py）
模拟器已经到达选择关卡的界面（即可以看到自由本名字、奖励的页面）
```
C:\Users\79261>cd /d D:\FGO-Automata-master

D:\FGO-Automata-master>adb connect 127.0.0.1:21503
connected to 127.0.0.1:21503

D:\FGO-Automata-master>python chentu.py
/sdcard/sh.png: 1 file pulled. 6.2 MB/s (2417720 bytes in 0.374s)
/sdcard/sh.png: 1 file pulled. 5.9 MB/s (2421372 bytes in 0.394s)
/sdcard/sh.png: 1 file pulled. 6.7 MB/s (2424910 bytes in 0.346s)
/sdcard/sh.png: 1 file pulled. 5.9 MB/s (2420982 bytes in 0.393s)
/sdcard/sh.png: 1 file pulled. 6.3 MB/s (2420126 bytes in 0.366s)
```

### 运行代码（example.py）
模拟器已经到达选择关卡的界面（即可以看到狗粮本名字、奖励的页面）
```
C:\Users\79261>adb connect 127.0.0.1:21503
connected to 127.0.0.1:21503

C:\Users\79261>cd /d D:\FGO-Automata-master

D:\FGO-Automata-master>python example.py
/sdcard/sh.png: 1 file pulled. 3.7 MB/s (2513660 bytes in 0.653s)
/sdcard/sh.png: 1 file pulled. 5.8 MB/s (2567608 bytes in 0.422s)
/sdcard/sh.png: 1 file pulled. 5.1 MB/s (2489003 bytes in 0.469s)
/sdcard/sh.png: 1 file pulled. 3.9 MB/s (2487221 bytes in 0.602s)

```

### 其他信息：

- python版本：3.8.2

- Package版本

```
Package               Version
--------------------- --------
configparser          5.0.0
cycler                0.10.0
kiwisolver            1.2.0
matplotlib            3.2.1
numpy                 1.18.5
opencv-contrib-python 4.2.0.34
opencv-python         4.2.0.34
Pillow                7.1.2
pip                   20.1.1
playsound             1.2.2
pyparsing             2.4.7
PyQt5                 5.15.0
PyQt5-sip             12.8.0
pytesseract           0.3.4
python-dateutil       2.8.1
setuptools            41.2.0
six                   1.15.0
you-get               0.4.1432
```

- Tesseract：

从https://github.com/UB-Mannheim/tesseract/wiki下载，64位，默认安装，已加入环境变量

- adb
Android Debug Bridge version 1.0.41
Version 29.0.5-5949299
Installed as D:\adb\adb.exe

- 模拟器
逍遥模拟器 7.2.1 版
分辨率：1920*1080，DPI288
端口：127.0.0.1:21503

- py程序文件
用config.bat创建
代码如下
```
from core.Automata import Automata 
# start  
fgo = Automata("assets/chentu.png", "assets/cba.png", sft=(0, 0)) 
fgo.quick_start(advance=True) 
# battle1 
fgo.select_servant_skill(1, 2) 
fgo.select_servant_skill(2) 
fgo.select_servant_skill(3, 2) 
fgo.select_servant_skill(7, 2) 
fgo.select_master_skill(3, 1, 1) 
fgo.select_master_skill(1) 
fgo.select_cards([7]) 
# battle2 
fgo.select_servant_skill(3) 
fgo.select_servant_skill(9, 2) 
fgo.select_servant_skill(6) 
fgo.select_cards([7]) 
# battle3 
fgo.select_servant_skill(1, 2) 
fgo.select_servant_skill(2) 
fgo.select_servant_skill(8) 
fgo.select_cards([7]) 
#finish 
fgo.finish_battle() 
```
助战、关卡图片：按照模板截取

另外，在试用[williamgateszhao](https://github.com/UB-Mannheim/tesseract/wiki)大佬的脚本时，也出现了类似的问题（一直截屏，但是不会继续执行）

**Comment by Meowcolm024** [comment]
模拟器啊，这个我还真没测试过。。。
但如果截的了图的话，点按操作理论上也没问题。
感觉比较可能的一个情况就是游戏界面上没有关卡模板对应的部分。
（不妨把目标和截图都发上来看看

**Comment by LorCamlot** [comment]
感谢大佬，破案了！
刚才在夜神和逍遥都试过了，果然是自己截的图程序不识别...
程序中用您assets文件夹里的图片是没问题的，但是自己截的图就不行了（关卡会选不了，助战也会不停刷新...）

以下是自己截的图（在非全屏模拟器下用win+shift+S截取，然后保存）
![chentu](https://user-images.githubusercontent.com/65847182/84587961-17ec3d00-ae56-11ea-8003-06642762b6a5.png)
![111](https://user-images.githubusercontent.com/65847182/84587971-3a7e5600-ae56-11ea-92ee-6a775b68002c.png)
![112](https://user-images.githubusercontent.com/65847182/84587974-3eaa7380-ae56-11ea-90e3-71e15225102b.png)

最后再次感谢大佬，祝大佬欧气满满，（圣晶）石无虚发！

**Comment by LorCamlot** [comment]
> 模拟器啊，这个我还真没测试过。。。
> 但如果截的了图的话，点按操作理论上也没问题。
> 感觉比较可能的一个情况就是游戏界面上没有关卡模板对应的部分。
> （不妨把目标和截图都发上来看看
> 
> 也建议试一下进入战斗之后逐行执行一下代码

啊，大佬，现在真的破案了！！！
是截图方式的问题，之前的截图是用window的截图，直接截取目标区域，得到的图像分辨率小
采用模拟器截图+裁剪后，没问题了！！

感谢大佬！祝大佬生活愉快，游戏丰收！
