### ISSUE TITLE
有目标的技能选择的问题

### ISSUE THREAD

**Issue by hbw0018** [Meowcolm024/FGO-Automata#26]
您好 是不是两次选择目标技能的等待时间太短了 连续执行两次选择目标技能会停住  中间插一个不选择目标技能会跳过它执行两次选择目标技能

![QQ截图20200919095039](https://user-images.githubusercontent.com/61693528/93656517-a841ab80-fa5d-11ea-9f37-0d1a61ed32ba.png)

![QQ截图20200919095212](https://user-images.githubusercontent.com/61693528/93656538-ce674b80-fa5d-11ea-9f79-00dd2ecb47f6.png)
先进行两次选择目标技能 只能进行一次 第二次完全不点击技能 没有任何后续操作 不进入下一回合 也不跳过执行

![QQ截图20200919095913](https://user-images.githubusercontent.com/61693528/93656703-d07dda00-fa5e-11ea-94bf-678ebdbdd278.png)
可以执行衣服的目标选择 然后执行没有目标技能 执行一次选择目标技能 然后停住

![QQ截图20200919100411](https://user-images.githubusercontent.com/61693528/93656784-83e6ce80-fa5f-11ea-8cb5-4012aff67118.png)
![QQ截图20200919100406](https://user-images.githubusercontent.com/61693528/93656786-88ab8280-fa5f-11ea-870e-c011ec9b28b9.png)
执行选择目标技能1 会跳过执行未选择目标技能 执行选择目标技能2 然后再次停住

**Comment by hbw0018** [comment]
![1](https://user-images.githubusercontent.com/61693528/93656952-f906d380-fa60-11ea-8e44-21a581a5caf5.png)
![2](https://user-images.githubusercontent.com/61693528/93656954-fa380080-fa60-11ea-8221-c9a283a15fc1.png)
![3](https://user-images.githubusercontent.com/61693528/93656956-fb692d80-fa60-11ea-9efc-347f419d57ee.png)
![4](https://user-images.githubusercontent.com/61693528/93656958-fc01c400-fa60-11ea-9e0a-f18acfdfb404.png)
![5](https://user-images.githubusercontent.com/61693528/93656962-fc9a5a80-fa60-11ea-890d-3d4751b5a48d.png)

**Comment by hbw0018** [comment]
执行两个选择目标技能，只能执行一个。 执行选目标技能1，执行未选择目标技能 ，执行选择目标技能2，会跳过无目标技能。是等待时间太短的问题吗？

**Comment by hbw0018** [comment]
请问等待时间的代码在哪，调一下技能间隔时间试试，谢谢您

**Comment by Meowcolm024** [comment]
啊，我觉得有可能，有个暂时的解决办法。
在`Automata.py` 里面 `select_servant_skill` 结尾加上
``` python
time.sleep(1)
```

**Comment by hbw0018** [comment]
def select_servant_skill(self, skill: int, tar: int = 0):
        """ Select Servant Skill
        Parameters
        ----------
            skill: int
        The id of the skill. 1~9 counted from left.

            tar: int, optional
        The id of target servant. 1~3 counted from left.
        (If the skill has target servant)

        Examples
        --------
        Here are examples::

            select_servant_skill(1) # skill w/o target servants
            select_servant_skill(3, 2) # skill w/ target servants
        """
        while not util.standby(util.get_sh(self.shifts), "assets/attack.png"):
            time.sleep(0.2)
        self.tap(crds.SERVANT_SKILLS[skill-1], 5, 5)
        time.sleep(1.5)
        if tar != 0:
            self.select_servant(tar)
这是技能选择那块 应该加在哪里 那个time.sleep(1.5)是技能等待时间吗

**Comment by hbw0018** [comment]
两次技能释放之间添加间隔，应该放在哪个位置。

**Comment by Meowcolm024** [comment]
不是那里，那个是点技能和选择目标的时间间隔，应该：
``` python
    if tar != 0:
        self.select_servant(tar)
        time.sleep(1)
```

**Comment by hbw0018** [comment]
Traceback (most recent call last):
  File "piao.py", line 1, in <module>
    from core.Automata import Automata
  File "C:\youxi\FGO-Automata-0.6.3\core\Automata.py", line 96
    time.sleep(1.5)
                  ^
TabError: inconsistent use of tabs and spaces in indentation
加完不能动了

**Comment by Meowcolm024** [comment]
> Traceback (most recent call last):
> File "piao.py", line 1, in
> from core.Automata import Automata
> File "C:\youxi\FGO-Automata-0.6.3\core\Automata.py", line 96
> time.sleep(1.5)
> ^
> TabError: inconsistent use of tabs and spaces in indentation
> 加完不能动了

啊这，Python的缩进是4个空格（不要用tab）
`time.sleep(1)`对其上面那一行就好了

**Comment by hbw0018** [comment]
![QQ截图20200919105931](https://user-images.githubusercontent.com/61693528/93657701-425a2180-fa67-11ea-817b-78499f250c8d.png)
![QQ截图20200919105948](https://user-images.githubusercontent.com/61693528/93657704-4423e500-fa67-11ea-8a15-7db713b4153b.png)
还是不行

**Comment by Meowcolm024** [comment]
`time.sleep(1)`的前面都要是空格才可以的

**Comment by hbw0018** [comment]
懂了

**Comment by hbw0018** [comment]
可以运行了，感谢您的帮助，就是间隔太短的问题，术呆的技能释放要比其它英灵久。

**Comment by hbw0018** [comment]
大佬还有个问题，关于结束一次运行
 # after-battle related
    def finish_battle(self):
        while not util.standby(util.get_sh(self.shifts), "assets/item.png"):
            xs = util.get_crd(util.get_sh(self.shifts), "assets/close.png")
            if len(xs) != 0:
                self.tap(xs[0])
            self.tap((660, 840), 40, 1)
            time.sleep(0.9)
        time.sleep(0.9)
        x = util.get_crd(util.get_sh(self.shifts), "assets/item.png")
        self.tap(x[0])
        print("[INFO] Battle Finished.")

    # FLAWED
    def is_finished(self) -> bool:
        time.sleep(0.5)
        return util.standby(util.get_sh(self.shifts), "assets/finish.png", 0.5)
程序在点击finish.png（下一项）的时候，就默认完成了一次执行。然后就会停留在close.png（关闭），再次出战 的界面上，必须手动点关闭才能进行下一次

**Comment by Meowcolm024** [comment]
> 大佬还有个问题，关于结束一次运行
> 
> # after-battle related
> ```
> def finish_battle(self):
>     while not util.standby(util.get_sh(self.shifts), "assets/item.png"):
>         xs = util.get_crd(util.get_sh(self.shifts), "assets/close.png")
>         if len(xs) != 0:
>             self.tap(xs[0])
>         self.tap((660, 840), 40, 1)
>         time.sleep(0.9)
>     time.sleep(0.9)
>     x = util.get_crd(util.get_sh(self.shifts), "assets/item.png")
>     self.tap(x[0])
>     print("[INFO] Battle Finished.")
> 
> # FLAWED
> def is_finished(self) -> bool:
>     time.sleep(0.5)
>     return util.standby(util.get_sh(self.shifts), "assets/finish.png", 0.5)
> ```
> 
> 程序在点击finish.png（下一项）的时候，就默认完成了一次执行。然后就会停留在close.png（关闭），再次出战 的界面上，必须手动点关闭才能进行下一次

请单独开另外一个issue
