### ISSUE TITLE
无法进行`连续战斗`

### ISSUE THREAD

**Issue by hbw0018** [Meowcolm024/FGO-Automata#27]
脚本结束一次运行

after-battle related
def finish_battle(self):
    while not util.standby(util.get_sh(self.shifts), "assets/item.png"):
        xs = util.get_crd(util.get_sh(self.shifts), "assets/close.png")
        if len(xs) != 0:
            self.tap(xs[0])
        self.tap((660, 840), 40, 1)
        time.sleep(0.9)
    time.sleep(0.9)
    x = util.get_crd(util.get_sh(self.shifts), "assets/item.png")
    self.tap(x[0])
    print("[INFO] Battle Finished.")

# FLAWED
def is_finished(self) -> bool:
    time.sleep(0.5)
    return util.standby(util.get_sh(self.shifts), "assets/finish.png", 0.5)
程序在点击finish.png（下一项）的时候，就默认完成了一次执行。然后就会停留在close.png（关闭），再次出战 的界面上，必须手动点关闭才能进行下一次

**Comment by hbw0018** [comment]
![QQ截图20200919173253](https://user-images.githubusercontent.com/61693528/93663995-32a9ff80-fa9e-11ea-8f16-4fb590ac7754.png)
这个界面点击下一项 就完成了一次运行
![QQ截图20200919173259](https://user-images.githubusercontent.com/61693528/93664014-4f463780-fa9e-11ea-8ab4-b01cf585dd10.png)
这个界面的关闭必须手动点击

**Comment by Meowcolm024** [comment]
哦这个啊，因为完全没有适配。
主要是因为当初国服没这个（那时日服好像开adb就不能启动）所以没有搞。
然后现在国服更新了这个技能，但我国服已经退坑了。（所以就鸽了）

---

**解决方案其实不难，如果您熟悉git能帮忙的话（提供1080p下截下来的模板图片），我应该能在明天把问题解决。**

**Comment by hbw0018** [comment]
好的，我应该截取哪几个部分的图片

**Comment by Meowcolm024** [comment]
我看到您已经fork了，那就需要把最新的（7d58952）PR到你的fork里面。
然后将模板图片添加到`assets/jp`里面，参照`assets/cn`的内容。

然后添加如下两张：

1. 包含`連続して`的图片，命名为`cont.png`
2. 包含`閉じる`的图片，命名为`cont_close.png`

注意：图片需要从设备上（ie模拟器）截下。也就是您制作模板图片的方式

**Comment by hbw0018** [comment]
完成 如需重复运行请运行该文件 正常运行请py ceshi.py
是否即刻运行? 1=是 2=否
请输入数字:1
请设置重复次数:1
请输入要运行的文件名(无需添加默认后缀.py,按Enter确认):ceshi
开始运行,次数为1次
Traceback (most recent call last):
  File "ceshi.py", line 1, in <module>
    from core.Automata import Automata
  File "C:\youxi\FGO-Automata-master\core\Automata.py", line 7, in <module>
    class Automata():
  File "C:\youxi\FGO-Automata-master\core\Automata.py", line 72, in Automata
    def select_servant_skill(self, skill: int, tar: int = 0, extend=false):
NameError: name 'false' is not defined
第1次运行完成
请按任意键继续. . .

您好，新的库还不能运行，我先把图片上传了

**Comment by Meowcolm024** [comment]
> 完成 如需重复运行请运行该文件 正常运行请py ceshi.py
> 是否即刻运行? 1=是 2=否
> 请输入数字:1
> 请设置重复次数:1
> 请输入要运行的文件名(无需添加默认后缀.py,按Enter确认):ceshi
> 开始运行,次数为1次
> Traceback (most recent call last):
> File "ceshi.py", line 1, in 
> from core.Automata import Automata
> File "C:\youxi\FGO-Automata-master\core\Automata.py", line 7, in 
> class Automata():
> File "C:\youxi\FGO-Automata-master\core\Automata.py", line 72, in Automata
> def select_servant_skill(self, skill: int, tar: int = 0, extend=false):
> NameError: name 'false' is not defined
> 第1次运行完成
> 请按任意键继续. . .
> 
> 您好，新的库还不能运行，我先把图片上传了

啊这是个typo，应该是`False` QAQ

**Comment by Meowcolm024** [comment]
操作是这样的：

1. 在[你的repository](https://github.com/hbw0018/FGO-Automata)里，点`Pull request`
2. 选择我的Master指向你的Master的PR，然后merge。这样上面应该会显示 equivalent
3. 然后有个`add file` 按钮可以上传文件

**Comment by Meowcolm024** [comment]
算了，要不这样，把`关闭`这个按钮的坐标发一下。

**Comment by hbw0018** [comment]
行 我实在不会用 不好意思 麻烦您了  x：650 y：850

**Comment by Meowcolm024** [comment]
没事。更新了一下。
在repo主页：
- 点击左上角`master`选择`dev`，右边有个绿色的`code`按钮，点`download zip`就好了
