### ISSUE TITLE
选择地图后选人报错

### ISSUE THREAD

**Issue by hbw0018** [Meowcolm024/FGO-Automata#32]
Traceback (most recent call last):
  File "ceshi.py", line 4, in <module>
    fgo.quick_start(advance=True)
  File "C:\youxi\FGO-Automata-dev\core\Automata.py", line 433, in quick_start
    self.select_checkpoint()
  File "C:\youxi\FGO-Automata-dev\core\Automata.py", line 221, in select_checkpoint
    if util.standby(self.aquire_screenshot(), crds.IMAGE["no_ap"]):
  File "C:\youxi\FGO-Automata-dev\core\util.py", line 58, in standby
    res = cv2.matchTemplate(img, template, cv2.TM_CCOEFF_NORMED)
cv2.error: OpenCV(4.4.0) C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-k8sx3e60\opencv\modules\imgproc\src\templmatch.cpp:588: error: (-215:Assertion failed) corr.rows <= img.rows + templ.rows - 1 && corr.cols <= img.cols + templ.cols - 1 in function 'cv::crossCorr'
您好，下了新的仓库，选择地图后进入选助战界面报错了

**Comment by Meowcolm024** [comment]
是连续战斗时报错吗？

**Comment by hbw0018** [comment]
不是，确认地图后，进入助战选择界面就报错了

**Comment by Meowcolm024** [comment]
看看有没有截到图

**Comment by Meowcolm024** [comment]
我又把东西改回去了，看看行不行（要注意模板图片的路径

**Comment by hbw0018** [comment]
没有进入截图

**Comment by Meowcolm024** [comment]
> 没有进入截图

助战图片放在哪里了？

**Comment by hbw0018** [comment]
跟以前一样 我直接复制的我的图

**Comment by Meowcolm024** [comment]
> 跟以前一样 我直接复制的我的图

就是在哪个文件夹？要和`crds.py`里面的对应。

**Comment by hbw0018** [comment]
assets文件夹

**Comment by Meowcolm024** [comment]
> assets文件夹

那就是图片路径不对。

要不放到`assets/cn`下面

要不放到`assets/jp`下面，然后修改`utils`里面：

```python
IMAGE_BASE = "assets/jp/"
```

**Comment by hbw0018** [comment]
error: protocol fault (couldn't read status): Connection reset by peer
adb: error: failed to get feature set: protocol fault (couldn't read status): Connection reset by peer
Traceback (most recent call last):
  File "ceshi.py", line 4, in <module>
    fgo.quick_start(advance=True)
  File "C:\youxi\FGO-Automata-dev\core\Automata.py", line 433, in quick_start
    self.select_checkpoint()
  File "C:\youxi\FGO-Automata-dev\core\Automata.py", line 212, in select_checkpoint
    self.wait(self.checkpoint)
  File "C:\youxi\FGO-Automata-dev\core\Automata.py", line 481, in wait
    while not util.standby(self.aquire_screenshot(), pic):
  File "C:\youxi\FGO-Automata-dev\core\util.py", line 58, in standby
    res = cv2.matchTemplate(img, template, cv2.TM_CCOEFF_NORMED)
cv2.error: OpenCV(4.4.0) C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-k8sx3e60\opencv\modules\imgproc\src\templmatch.cpp:588: error: (-215:Assertion failed) corr.rows <= img.rows + templ.rows - 1 && corr.cols <= img.cols + templ.cols - 1 in function 'cv::crossCorr'

第1次运行完成
请按任意键继续. . . 

修改完路径 连地图都不进了 直接报错了

**Comment by Meowcolm024** [comment]
> error: protocol fault (couldn't read status): Connection reset by peer
> adb: error: failed to get feature set: protocol fault (couldn't read status): Connection reset by peer
> Traceback (most recent call last):
> File "ceshi.py", line 4, in 
> fgo.quick_start(advance=True)
> File "C:\youxi\FGO-Automata-dev\core\Automata.py", line 433, in quick_start
> self.select_checkpoint()
> File "C:\youxi\FGO-Automata-dev\core\Automata.py", line 212, in select_checkpoint
> self.wait(self.checkpoint)
> File "C:\youxi\FGO-Automata-dev\core\Automata.py", line 481, in wait
> while not util.standby(self.aquire_screenshot(), pic):
> File "C:\youxi\FGO-Automata-dev\core\util.py", line 58, in standby
> res = cv2.matchTemplate(img, template, cv2.TM_CCOEFF_NORMED)
> cv2.error: OpenCV(4.4.0) C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-k8sx3e60\opencv\modules\imgproc\src\templmatch.cpp:588: error: (-215:Assertion failed) corr.rows <= img.rows + templ.rows - 1 && corr.cols <= img.cols + templ.cols - 1 in function 'cv::crossCorr'
> 
> 第1次运行完成
> 请按任意键继续. . .
> 
> 修改完路径 连地图都不进了 直接报错了

**图片路径要和图片位置匹配啊！**
**用于识别的模板图片和关卡/助战的路径是分开的。**

下面举个例子：

假如所有除**助战/关卡**的图片都放到了`assets/jp`里面，`crds.py`就应该修改：

```python
IMAGE_BASE = "assets/jp/"
```

而你的**助战/关卡**图片如果放到了`assets`里面，脚本文件就应该是：

```python
fgo = Automata("assets/checkpoint.png", "assets/support.png")
```

**Comment by hbw0018** [comment]
[Autumata.txt](https://github.com/Meowcolm024/FGO-Automata/files/5250022/Autumata.txt)
这是我现在使用的0.63的文件 其余都没有进行修改，可以进行到 ，关闭/继续战斗的界面。
gubhit一直下载不下来，没法上传本地仓库
