### ISSUE TITLE
連続して 报错

### ISSUE THREAD

**Issue by cocomber1** [Meowcolm024/FGO-Automata#34]
卡在連続出擊版面,不会点閉じる
用的是dev版本

![1](https://user-images.githubusercontent.com/71925484/94338263-7911d800-0023-11eb-9146-09cfed2e49d9.jpg)
![2](https://user-images.githubusercontent.com/71925484/94338265-7a430500-0023-11eb-8313-d3a80c18013b.jpg)

**Comment by Meowcolm024** [comment]
请问是master branch/ 0.6.3的版本还是dev branch的版本？
________________________________

**Comment by cocomber1** [comment]
是dev的版本,cont=True

**Comment by Meowcolm024** [comment]
这个似乎是图像识别错误，我稍后检查一下

**Comment by Meowcolm024** [comment]
好的，应该是bug

**Comment by Meowcolm024** [comment]
现在pull下来，在试一下（忘记加多一对括号了orz

**Comment by cocomber1** [comment]
谢谢大佬,实测没问题
没想到大佬这么快回覆,吓一跳了ww
