### ISSUE TITLE
更新助战列表 报错

### ISSUE THREAD

**Issue by cocomber1** [Meowcolm024/FGO-Automata#36]
脚本开了高级助战
情况大概是第一次选助战时选不到的话会自动按更新列表
但是第二次还是识别不了助战就直接报错了 (看脚本应该default是刷新3遍吧?

![未命名](https://user-images.githubusercontent.com/71925484/94707708-54e12e80-0376-11eb-992b-204a87cc35d4.jpg)

**Comment by Meowcolm024** [comment]
感觉是个bug，但和更新次数无关。
估计是因为点第二次更新的时候10s倒计时还没结束。

**Comment by Meowcolm024** [comment]
改了一下，可以把dev branch的版本pull下来看看行不行:)

**Comment by cocomber1** [comment]
嗯,实测没问题了,能多次更新助战

另外还有一个提问
![Screenshot_2020-10-01-14-27-53](https://user-images.githubusercontent.com/71925484/94776032-8815d300-03f3-11eb-94f4-eb200eec5df4.png)

就是无限池会有特写动画,![attack](https://user-images.githubusercontent.com/71925484/94775910-4b49dc00-03f3-11eb-89df-7470d713d304.png)出来了但是Attack button还没出来
尝试过加大sleep的时间或者识别改为![attack1](https://user-images.githubusercontent.com/71925484/94775962-64528d00-03f3-11eb-98c7-4ba9bee2bfee.png),不过看来效率还有识别都不太好
大佬有什么好的提议吗?

现在我只是很土炮的加了句点击在这里
while not util.standby(util.get_sh(self.shifts), crds.IMAGE["attack"]):
            self.tap((1300, 300))
            time.sleep(0.2)
