### ISSUE TITLE
能加入吃铜苹果的选项吗

### ISSUE THREAD

**Issue by cocomber1** [Meowcolm024/FGO-Automata#39]
抽池子上千个铜苹果在仓库,手动吃有点痛苦
希望大佬能加上吃铜苹果的选项,感谢

**Comment by Meowcolm024** [comment]
在搞了。
不过要注意的是铜苹果加的AP少，要注意数量。而且会看到吃一个苹果尝试进一次关卡的奇观哈哈哈
