### ISSUE TITLE
util imdecode error

### ISSUE THREAD

**Issue by Zhen-Bo** [Meowcolm024/FGO-Automata#45]
![image](https://user-images.githubusercontent.com/30999421/104021413-ab71ca80-51f9-11eb-973c-37789477f13a.png)
如果改成subporcess的方式的話貌似在import util的時候就會去把它執行過一次,而這時如果沒有adb開啟並連接的話會導致imdecode那邊出現錯誤
解決辦法看是要在util最上面加個判斷句,判斷如果沒有開啟adb的時候就開啟
而我的解決方法是把adb包成一個class然後在第一次開啟程式的時候就會先進行重啟

**Comment by Meowcolm024** [comment]
啊这，subprocess相关的我不是很懂QAQ。劳驾了。
________________________________

**Comment by Zhen-Bo** [comment]
那我改完就直接推一個PR?
主要是因為台日版你們是坐在一起,如果現在陸版能跑然後日版沒法跑,我把日版的改的能跑了之後又怕陸版的不能跑Orz

**Comment by Meowcolm024** [comment]
直接开pr就好了 :)
________________________________

**Comment by Zhen-Bo** [comment]
推了,話說日版沒有做自動連續戰鬥的判斷喔🤔

**Comment by Meowcolm024** [comment]
> 推了,話說日版沒有做自動連續戰鬥的判斷喔🤔

https://github.com/Meowcolm024/FGO-Automata/blob/b3961092532b0e91b1e33cb448c7b0464fdd0e8f/core/Automata.py#L383

这一个函数有处理，采取简单粗暴的方法：不继续，然后重新点进关卡。
虽然速度慢点，但可以重用前面的逻辑:)

**Comment by Zhen-Bo** [comment]
了解了🤔
