### ISSUE TITLE
一直停在daemon started successfully不动

### ISSUE THREAD

**Issue by q793200739** [Meowcolm024/FGO-Automata#49]
![Uploading image.png…]()
一直停在这里不动

**Comment by q793200739** [comment]
![image](https://user-images.githubusercontent.com/67819437/120612740-16ad8900-c488-11eb-8ca3-d86ff1edcee5.png)

**Comment by q793200739** [comment]
没事了，原来是截的图没匹配上，不过截图要怎么截才能较好地被识别啊

**Comment by Meowcolm024** [comment]
使用设备上的截图（就是假如用手机的话就在手机上截图完之后传到电脑

用adb截图也可以

2021/06/03 午後5:16、q793200739 ***@***.***>のメール:

﻿

没事了，原来是截的图没匹配上，不过截图要怎么截才能较好地被识别啊

**Comment by q793200739** [comment]
解决了，adb截图可以识别，谢谢啦，不过qq截图不行真奇怪。
