### ISSUE TITLE
一些建議想討論

### ISSUE THREAD

**Issue by Zhen-Bo** [Meowcolm024/FGO-Automata#51]
想問下,可以跟你要個QQ號或是信箱或是discord or 其他聯絡方式嗎?
主要有些建議直接可以說明比較方便
PS:因為我懶癌發作不想再重看code修改後發起pull request
或是你可以加我
Discord:(´_ゝ`)#9487
如果不方便在這邊直接公開聯繫方式的話可以寄信到我信箱:sharekevin001958@gmail.com

**Comment by Meowcolm024** [comment]
那我开一个Github Discussion :D

**Comment by Zhen-Bo** [comment]
原來還有這種功能🤔

**Comment by Meowcolm024** [comment]
开了一个testing的discussion，可以去试试OWO
