### ISSUE TITLE
自動補充AP失敗

### ISSUE THREAD

**Issue by Novicewhite** [Meowcolm024/FGO-Automata#54]
Language: 
  - English
  - 中文

Please describe the issue specifically. It's recommended to attach the output log and the screenshot.
请具体描述您遇到的问题。建议附上输出记录和截图。
吃蘋果的時候報錯了，其他功能正常
![Screenshot 2021-08-12 035446](https://user-images.githubusercontent.com/37052339/129094375-51bea33d-b22d-452f-a5c3-75da2dc8ca99.png)

**Comment by Meowcolm024** [comment]
呃…能不能发一下你写的脚本。
opencv这个错误估计是没加载到图片

iPhoneから送信

2021/08/12 午前3:55、Novicewhite ***@***.***>のメール:

﻿

Language:

  *   English
  *   中文

Please describe the issue specifically. It's recommended to attach the output log and the screenshot.
请具体描述您遇到的问题。建议附上输出记录和截图。
吃蘋果的時候報錯了，其他功能正常
[Screenshot 2021-08-12 035446]<https://user-images.githubusercontent.com/37052339/129094375-51bea33d-b22d-452f-a5c3-75da2dc8ca99.png>

**Comment by Novicewhite** [comment]
感谢回复！我检查了一下脚本和英文版的README，发现README和在WIKI里的脚本配置视频的setapples用法有不同，我之前是按照视频写的，现在按照README改正后能够正常吃苹果了。
