### ISSUE TITLE
连接Mumu模拟器时报错

### ISSUE THREAD

**Issue by PpWenCC** [Meowcolm024/FGO-Automata#55]
Language: 
  - English
  - 中文

Please describe the issue specifically. It's recommended to attach the output log and the screenshot.
请具体描述您遇到的问题。建议附上输出记录和截图。

每次运行脚本之前连接的模拟器就会断开连接 但是在真机上可以运行。使用mumu模拟器 分辨率是1920*1080 DPI 480
以下为报错

`(venvp) E:\Programme\Python\FGO-Automata-master>adb devices & python Qp.py & adb devices
List of devices attached
127.0.0.1:7555  device

* daemon not running; starting now at tcp:5037
* daemon started successfully
error: no devices/emulators found
Traceback (most recent call last):
  File "Qp.py", line 1, in <module>
    from core import util, crds
  File "E:\Programme\Python\FGO-Automata-master\core\util.py", line 78, in <module>
    def standby(images=get_sh((0, 0)), tmp: str = None, threshold: float = 0.85) -> bool:
  File "E:\Programme\Python\FGO-Automata-master\core\util.py", line 58, in get_sh
    img = screencap()
  File "E:\Programme\Python\FGO-Automata-master\core\util.py", line 71, in screencap
    image_bytes, dtype='uint8'), cv2.IMREAD_COLOR)
cv2.error: OpenCV(4.4.0) C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-iw3y3ir8\opencv\modules\imgcodecs\src\loadsave.cpp:753: error: (-215:Assertion failed) !buf.empty() in function 'cv::imdecode_'

List of devices attached

`

**Comment by Meowcolm024** [comment]
模拟器的Android版本是多少

iPhoneから送信

2021/08/12 午後11:59、Pika_ice ***@***.***>のメール:

﻿

Language:

  *   English
  *   中文

Please describe the issue specifically. It's recommended to attach the output log and the screenshot.
请具体描述您遇到的问题。建议附上输出记录和截图。

每次运行脚本之前连接的模拟器就会断开连接 但是在真机上可以运行。使用mumu模拟器 分辨率是1920*1080 DPI 480
以下为报错

`(venvp) E:\Programme\Python\FGO-Automata-master>adb devices & python Qp.py & adb devices
List of devices attached
127.0.0.1:7555 device

  *   daemon not running; starting now at tcp:5037
  *   daemon started successfully
error: no devices/emulators found
Traceback (most recent call last):
File "Qp.py", line 1, in
from core import util, crds
File "E:\Programme\Python\FGO-Automata-master\core\util.py", line 78, in
def standby(images=get_sh((0, 0)), tmp: str = None, threshold: float = 0.85) -> bool:
File "E:\Programme\Python\FGO-Automata-master\core\util.py", line 58, in get_sh
img = screencap()
File "E:\Programme\Python\FGO-Automata-master\core\util.py", line 71, in screencap
image_bytes, dtype='uint8'), cv2.IMREAD_COLOR)
cv2.error: OpenCV(4.4.0) C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-iw3y3ir8\opencv\modules\imgcodecs\src\loadsave.cpp:753: error: (-215:Assertion failed) !buf.empty() in function 'cv::imdecode_'

List of devices attached

`

**Comment by PpWenCC** [comment]
感谢大佬回复！
模拟器是安卓6.0.1
![屏幕截图 2021-08-13 090257](https://user-images.githubusercontent.com/57895302/129288707-255228ed-2f85-460f-9d44-7304db106b57.png)

**Comment by Meowcolm024** [comment]
噢，因为之前更新了截图获取方式，好像需要Android 7或以上版本。
参考：
https://github.com/Meowcolm024/FGO-Automata/blob/26572827857ad2551920e878bc7201afe2ff9aec/core/util.py#L65

**Comment by PpWenCC** [comment]
感谢！！我去尝试更新一下mumu模拟器的安卓版本
