### ISSUE TITLE
初始出星会影响使用

### ISSUE THREAD

**Issue by zhangsan1025** [Meowcolm024/FGO-Automata#56]
如果带的礼装有出星，有可能会吞掉开始的技能，比如此次国服泳装活动
推测有额外buff也会有类似问题
另外更新助战之后滑动寻找助战太快了，还没加载出来就滑过了
感谢大佬

**Comment by Meowcolm024** [comment]
第一个问题：可能是是出星的时候占用了一点时间，所以导致点不到。。。随便加一个像`time.sleep(0.5)`的延时就好了。
第二个其实自己写也很简单，大概就三部分：1.点抽卡；2.狂点屏幕直到抽完；3.点继续抽卡
基本上就是这样(比如要连续抽的话）：
``` python
shiki = Automata(None, None)
shiki.tap(util.get_crd(util.get_sh(shiki.shifts), <抽卡按钮模板图片路径>))
while True:
    shiki.wait(<抽卡结束模板图片路径>)
    shiki.tap(util.get_crd(util.get_sh(shiki.shifts), <继续抽卡按钮模板图片路径>))
```
呃。。。还是挺复杂的(⊙﹏⊙)

**Comment by zhangsan1025** [comment]
感谢大佬回答
其实我学过一点代码，不过目前是十窍通了九窍，之前用autojs写的弄着弄着就报错了，所以来白嫖大佬的成果
有时间一定看代码学习一下
