### ISSUE TITLE
I have a good idea

### ISSUE THREAD

**Issue by GiantZwlin** [Meowcolm024/FGO-Automata#9]
I think this tool is using adb to control the mobile phone,which means the PC should be connected to the real phone or use  the simulator. I have a Raspberry Pi,I think it can replace the PC. Do you have suggestions about this idea? Or I misunderstand the usage of the repo?

**Comment by Meowcolm024** [comment]
Like running this script on a  _Raspberry Pi_ (which is connected to an Android device/simulator)?
orz

**Comment by GiantZwlin** [comment]
Yes

**Comment by Meowcolm024** [comment]
I guess the current one can actually do it...

**Comment by GiantZwlin** [comment]
Perhaps,But  the demo.py is not so friendly,I am trying to understand your code. Should I open the fgo first,and then run the script?

**Comment by Meowcolm024** [comment]
Nope, the `demon.py` and `config.bat` are used to setup the script. You need to write your own script following the instructions

**Comment by GiantZwlin** [comment]
I have some questions,can you give me your contacts? My email address is giantzwlin@gmail.com

**Comment by GiantZwlin** [comment]
我应该从FGO的哪个界面开始？我还是先了解下opencv吧，这个库我没用过。

**Comment by Meowcolm024** [comment]
关卡选择开始（像是：““开启宝物之门”）

**Comment by Meowcolm024** [comment]
但严格的来说可以从任意界面开始
